# Reading Error Messages (Intro - Debugging)
# Variable Assignment Lab (Intro - Variables)
# TDD, RSpec, Learn (Intro - Methods)
# Interpolation Super Power (Intro - Methods)
# gets CLI Input (Intro - Command Line Applications)
# Greeting CLI Lab (Intro - Command Line Applications)
# Rspec Fizzbuzz (Intro - Logic and Conditions)
# While and Until Loops Lab (Intro - Loops)
